Implement performance metrics BehaveTree Node
bitbrain/beehave pull request #103
Opened 2023-01-22 22:06 UTC by goudcode

## Description

I've implemented the performance per tree in the Godot engine profiler.
Time is being showed in nanosecconds and tree will be automatically added and removed to the profiler.

It might be better to disable all the metric code when running in release mode, example: use `if OS.is_debug_build()`
Any ideas are welcome.

## Addressed issues
#89 

## Screenshots
![afbeelding](https://user-images.githubusercontent.com/23435053/213942849-0aac2de6-a19d-412a-891d-52e82ea9634c.png)

2023-01-23 09:12 UTC, bitbrain requested changes
Very good start! Apart from a few smaller comments this looks generally good.

Could we also add additional metrics like described on #89?

| Metric Name | Description |
|---|---|
| `beehave/tree_id/process_time` | The total process time per frame tick for the whole behaviour tree |
| `beehave/node_count` | The number of total beehave nodes in the scene |
| `beehave/active_count` | Number of active behaviour trees in the scene |

Also reminder, that there is no need to check for debug mode, as Godot will only query the monitors inside the editor anyways and ensures not to call these in production mode.

2023-01-23 09:12 UTC, bitbrain commented on addons/beehave/nodes/beehave_tree.gd
> +var _tree_metric_name : String
we may want to give this a better name: as it is tracking the `process_time` of this tree, perhaps something like this:
```suggestion
var _process_time_metric_name : String
```
(we are inside the tree already so using "tree" is redundant)

2023-01-23 09:12 UTC, bitbrain commented on addons/beehave/nodes/beehave_tree.gd
> +	_tree_metric_name = "beehave/process_time/%s(%s)" % [parent_name, get_instance_id()]
From a structural perspective, we may want to have multiple metrics as part of the same tree. Therefore, I'd group them differently:
```suggestion
	_tree_metric_name = "beehave/%s-%s/process_time" % [parent_name, get_instance_id()]
```

2023-01-23 09:12 UTC, bitbrain commented on addons/beehave/nodes/beehave_tree.gd
> +	var parent_name = get_parent().name
Using `get_parent()` here is wrong, as there are different ways to associate a node to a tree (see `actor_node_path` export property)
```suggestion
	var parent_name = actor.name
```

2023-01-23 12:21 UTC, bitbrain commented on addons/beehave/nodes/beehave_tree.gd
> +func _get_tree_metric() -> float:
Oh, this method also should be renamed to something like this:
```suggestion
func _get_process_time_metric_value() -> float:
```

2023-01-25 17:21 UTC, goudcode commented
The metric is now registered in the ready() function instead of the _enter_tree().
The reason for this is that the actor was not known in that function.

2023-01-26 08:43 UTC, bitbrain approved these changes
Thank you for your contribution!

2023-01-26 08:44 UTC, merged